baseURL = "https://dannyagus.com/"
languageCode = "id"
title = "Danny Agus"
theme = "PaperMod"
pagination.pagerSize = 5
ShowToc = true
TocOpen = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  env = "production"
  ShowSearch = true
  ShowArchive = true
  showDate = true
  ShowPostNavLinks = true
  googleAnalytics = "G-H233N3KGXJ"

[params.homeInfoParams]
  Title = "Selamat datang 👋"
  Content = "Ini blog saya. Kumpulan tulisan, tips, dan dokumentasi pribadi. Hubungi saya di danny@dwan.co.id!"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Search"
  url = "search/"
  weight = 2

[[menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 5



[outputs]
  home = ["HTML", "JSON"]